// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.ied.component;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class PageComponent extends RichDeclarativeComponent {

  public PageComponent() {
  }



}
