// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.ied.component;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;

public class PageTag extends RichDeclarativeComponentTag {

  public PageTag() {
  }

  public String getComponentType() {
    return "com.ied.component.PageComponentType";
  }

  protected String getViewId() {
    return "/component/page.jsf";
  }

  protected RichDeclarativeComponent createComponent() {
    return new PageComponent();
  }

}
